# ~/.config/starship.toml

add_newline = false

[battery]
disabled = true

[directory]
truncation_length = 0

[git_status]
disabled = true

[line_break]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true

[java]
disabled = true
